name: portfolio ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Backend dependencies
        working-directory: backend
        run: npm install

      - name: Run Backend tests
        working-directory: backend
        run: npm test

      - name: Build Backend
        working-directory: backend
        run: npm run build

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend dependencies
        working-directory: my-app
        run: npm install

      - name: Run Frontend tests
        working-directory: my-app
        run: npm test

      - name: Build Frontend
        working-directory: my-app
        run: npm run build
